export const COUNTRY_NAMES: Record<string, string> = {
  US: "Estados Unidos",
  BR: "Brasil",
  MX: "México",
  AR: "Argentina",
  CO: "Colômbia",
  CL: "Chile",
  PE: "Peru",
  EC: "Equador",
  VE: "Venezuela",
  UY: "Uruguai",
  PY: "Paraguai",
  BO: "Bolívia",
  ES: "Espanha",
  PT: "Portugal",
  GB: "Reino Unido",
  CA: "Canadá",
  DE: "Alemanha",
  FR: "França",
  IT: "Itália",
  AT: "Áustria",
  CH: "Suíça",
  NL: "Holanda",
  BE: "Bélgica",
  PL: "Polônia",
  SE: "Suécia",
  NO: "Noruega",
  DK: "Dinamarca",
  FI: "Finlândia",
  IE: "Irlanda",
  CZ: "República Tcheca",
  GR: "Grécia",
  RO: "Romênia",
  HU: "Hungria",
  AU: "Austrália",
  NZ: "Nova Zelândia",
  JP: "Japão",
  IN: "Índia",
  CN: "China",
  KR: "Coreia do Sul",
  SG: "Singapura",
  AE: "Emirados Árabes",
  ZA: "África do Sul",
  IL: "Israel",
  TR: "Turquia",
  RU: "Rússia",
  UA: "Ucrânia",
  MT: "Malta",
  LU: "Luxemburgo",
  HR: "Croácia",
  SK: "Eslováquia",
  SI: "Eslovênia",
  BG: "Bulgária",
  LT: "Lituânia",
  LV: "Letônia",
  EE: "Estônia",
  CY: "Chipre",
  IS: "Islândia",
};
